package nz.co.senanque.pizzabundle;

import java.util.Arrays;
import java.util.List;

import nz.co.senanque.perspectivemanager.Blackboard;
import nz.co.senanque.perspectivemanager.BlackboardListener;
import nz.co.senanque.pizzaorder.instances.OrderItem;
import nz.co.senanque.vaadinsupport.MaduraPropertyWrapper;
import nz.co.senanque.vaadinsupport.application.MaduraSessionManager;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

/**
 * @author Roger Parkinson
 *
 */
public class Layout extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private CssLayout embedded_1;
	@AutoGenerated
	private ProductForm productForm_1;
	@AutoGenerated
	private TextField textUserName;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	private static final long serialVersionUID = -6831508077127159490L;
	private Blackboard m_blackboard;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
    private final MaduraSessionManager m_maduraSessionManager;
	public MaduraSessionManager getMaduraSessionManager() {
		return m_maduraSessionManager;
	}
	public Layout(MaduraSessionManager maduraSessionManager) {
		m_maduraSessionManager = maduraSessionManager;
		buildMainLayout();
		productForm_1.setFieldList(Arrays.asList(new String[]{"base","size","grain","topping","testDate","testDouble","testing","amount"}));
		setCompositionRoot(mainLayout);
	}
	public Blackboard getBlackboard() {
		return m_blackboard;
	}
	public void setBlackboard(Blackboard blackboard) {
		m_blackboard = blackboard;
		m_blackboard.add(new BlackboardListener(){

			public void valueChanged(Object value) {
				textUserName.setValue(value);
			}

			public String getName() {
				return "userName";
			}});
	}
	public void setItemDataSource(BeanItem<OrderItem> beanItem) {
		productForm_1.setItemDataSource(beanItem);
	}
	public void save() {
		BeanItem<OrderItem> beanItem = (BeanItem<OrderItem>)productForm_1.getItemDataSource();
		m_blackboard.publish("orderItem", beanItem.getBean());
	}
	public List<MaduraPropertyWrapper> getProperties()
	{
		return productForm_1.getItemDataSourceProperties();
	}
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// textField_1
		textUserName = new TextField();
		textUserName.setCaption("User Name");
		textUserName.setImmediate(false);
		textUserName.setWidth("-1px");
		textUserName.setHeight("-1px");
		textUserName.setSecret(false);
		mainLayout.addComponent(textUserName);
		
		// productForm_1
		productForm_1 = new ProductForm(m_maduraSessionManager);
		productForm_1.setImmediate(true);
		productForm_1.setWidth("360px");
		productForm_1.setHeight("-1px");
		mainLayout.addComponent(productForm_1);
		
		// embedded_1
		embedded_1 = new CssLayout();
		embedded_1.setStyleName("login-logo");
		embedded_1.setImmediate(false);
		embedded_1.setWidth("-1px");
		embedded_1.setHeight("-1px");
		embedded_1.setMargin(false);
		mainLayout.addComponent(embedded_1);
		
		return mainLayout;
	}
}
